server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: mysql://ntqdah1h2dlb5ycj:k2cv83xur4jtbn3h@a07yd3a6okcidwap.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/crimcvkgbiw65pj6
    username: ntqdah1h2dlb5ycj
    password: k2cv83xur4jtbn3h

    #Chạy local
#    url: jdbc:mysql://localhost:3306/customer
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 9        # Giới hạn số kết nối tối đa
      idle-timeout: 600000         # Thời gian tối đa (ms) giữ kết nối không hoạt động (ở đây là 10 phút)
      max-lifetime: 1800000        # Thời gian tối đa sống của một kết nối (ở đây là 30 phút)
      connection-timeout: 30000    # Thời gian tối đa để chờ kết nối mới
      validation-timeout: 5000     # Thời gian tối đa để kiểm tra kết nối
      leak-detection-threshold: 15000 # Thời gian phát hiện rò rỉ kết nối (ở đây là 15 giây)
      connection-test-query: SELECT 1    # Kiểm tra kết nối hợp lệ

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
