server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://bqmayq5x95g1sgr9.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/dhvb5jajzm106gw6"
    username: nyhufdmq8i2gt0hn
    password: xqicb64jip3por7s

  jpa:
    hibernate:
      ddl-auto: update
