spring:
  datasource:
    url: jdbc:mysql://us-cluster-east-01.k8s.cleardb.net/heroku_579adff8c5844de?reconnect=true
    username: b15024aa3acf96
    password: 38503ab8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
