server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: mysql://vwtdq988jt3dy6iy:tmgrin7e18nc8the@otwsl2e23jrxcqvx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/d92ebi01a14uydco
    username: vwtdq988jt3dy6iy
    password: tmgrin7e18nc8the
    hikari:
      maximum-pool-size: 9        # Giới hạn số kết nối tối đa
      idle-timeout: 600000         # Thời gian tối đa (ms) giữ kết nối không hoạt động (ở đây là 10 phút)
      max-lifetime: 1800000        # Thời gian tối đa sống của một kết nối (ở đây là 30 phút)
      connection-timeout: 30000    # Thời gian tối đa để chờ kết nối mới
      validation-timeout: 5000     # Thời gian tối đa để kiểm tra kết nối
      leak-detection-threshold: 15000 # Thời gian phát hiện rò rỉ kết nối (ở đây là 15 giây)
      connection-test-query: SELECT 1    # Kiểm tra kết nối hợp lệ

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
